Update app's level
YunoHost/apps pull request #1060
Opened 2021-01-23 14:52 UTC by yalh76

- [ ] [ihatemoney](https://ci-apps.yunohost.org/ci/job/964)
- [ ] [invidious](https://ci-apps.yunohost.org/ci/apps/invidious/)
- [ ] [mastodon](https://ci-apps.yunohost.org/ci/job/899)
- [ ] [peertube-search-index](https://ci-apps.yunohost.org/ci/job/953)

2021-01-23 15:01 UTC, ericgaspar commented
- [x] [CryptPad](https://github.com/YunoHost-Apps/cryptpad_ynh/pull/59)
- [ ] [Mailman](https://github.com/YunoHost-Apps/mailman_ynh/pull/23)

2021-01-24 09:48 UTC, ericgaspar requested changes

2021-01-24 09:48 UTC, ericgaspar commented on apps.json
> +        "level": 6,
```suggestion
        "level": 8,
```

2021-01-24 22:14 UTC, ericgaspar approved these changes

2021-01-24 22:14 UTC, ericgaspar commented on apps.json
> +        "level": 4,
```suggestion
        "level": 8,
```

2021-01-24 22:16 UTC, ericgaspar approved these changes

2021-01-24 22:17 UTC, alexAubin approved these changes

2021-01-26 00:58 UTC, merged