Codepad
YunoHost/apps pull request #1172
Opened 2021-06-04 16:28 UTC by Stylix58

2021-06-04 16:31 UTC, ericgaspar requested changes

2021-06-04 16:31 UTC, ericgaspar commented on apps.json
> +    }
```suggestion
    "codepad": {
        "branch": "master",
        "category": "dev",
        "revision": "HEAD",
        "state": "working",
        "subtags": [
            "programming"
        ],
        "url": "https://github.com/YunoHost-Apps/codepad_ynh"
    }
```

2021-06-05 08:56 UTC, ericgaspar requested changes

2021-06-05 08:56 UTC, ericgaspar commented on apps.json
>      }
```suggestion
    },
```

2021-06-05 09:04 UTC, ericgaspar approved these changes

2021-06-05 09:04 UTC, Stylix58 commented
Ok! It is resolved!
You can merge now?

2021-06-05 09:05 UTC, merged