Add to catalog
YunoHost/apps pull request #1241
Opened 2021-09-18 20:31 UTC by ericgaspar

* Add n8n to catalog

2021-09-19 08:40 UTC, tituspijean approved these changes

2021-09-20 07:37 UTC, fflorent commented
Can you tell me what do you think of this issue?

https://github.com/YunoHost-Apps/n8n_ynh/issues/6 (*Not totally free license*)

If I quote [your documentation](https://yunohost.org/en/contribute/packaging_apps/quality_tests/yep):
> The application list apps.json only accept packages with a free license, as well as the license for the contained application. Some free applications require non-free dependencies (example: MP3, drivers, etc.). In this case, you should add &dep-non-free to the acronym and if possible give details in the README.md of the package, in this case the integration will be accepted on a case-by-case basis.

I don't know whether it would be compatible with the apps.json file here.

2021-09-20 08:18 UTC, tituspijean commented
That's a valid remark! I think we cannot allow such license in the catalog. 😞

2021-11-15 05:41 UTC, Limezy commented
>  😞 Maybe it is time to revive the non-free apps list.

@tituspijean I think I found the exact same problem for my Outline app... 
Its licence is "Business Source License 1.1" (https://github.com/outline/outline/blob/main/LICENSE)

Do you confirm that I can't add it to the app catalog ? 😢 😭

2022-08-08 07:33 UTC, ericgaspar commented
@tituspijean I propose to merge this with the addition of the licence antifeature

2022-08-08 08:34 UTC, fflorent commented
LGTM

2022-08-12 20:21 UTC, nsakibp commented
Please add

2022-08-13 14:29 UTC, tituspijean requested changes

2022-08-13 14:29 UTC, tituspijean commented on apps.json
> +            "Not totally free upstream"
```suggestion
            "not-totally-free"
```

2022-08-13 14:29 UTC, tituspijean approved these changes

2022-08-13 14:49 UTC, merged