Add Ecko (Mastodon fork)
YunoHost/apps pull request #1265
Opened 2021-11-10 18:28 UTC by weex

Repo doesn't exist at this instant but working to transfer it from from weex/ecko_ynh to YunoHost-Apps.

2021-11-10 19:18 UTC, yalh76 requested changes

2021-11-10 19:18 UTC, yalh76 commented on apps.json
> +        "level": 7,
```suggestion
```

level will be calculated automatically

2021-11-10 19:18 UTC, yalh76 commented on apps.json
> +        "branch": "master",
```suggestion
```

Branch is not required

2021-11-10 19:37 UTC, weex commented
Updated to remove those two lines.

2021-11-13 07:11 UTC, tituspijean approved these changes
Thank you for your work, and welcome!

2021-11-13 18:19 UTC, yalh76 approved these changes

2021-11-13 18:19 UTC, merged