Add Compteur du Gase to the application list
YunoHost/apps pull request #1314
Opened 2022-01-24 21:39 UTC by Jojo144

Le compteur du Gase is a software to manage products, stocks and people of self-managed grocery.

2022-01-24 21:52 UTC, tituspijean requested changes

2022-01-24 21:52 UTC, tituspijean commented on apps.json
> +        "url": "https://github.com/Jojo144/compteur_du_gase_ynh
```suggestion
        "url": "https://github.com/Jojo144/compteur_du_gase_ynh"
```

2022-01-25 07:25 UTC, Jojo144 commented
@tituspijean Thanks!

2022-01-25 07:28 UTC, tituspijean approved these changes

2022-01-25 07:28 UTC, merged