Add potential alternatives key in catalog, taken from Framasoft
YunoHost/apps pull request #1488
Opened 2022-08-07 15:14 UTC by ketsapiwiq

https://github.com/YunoHost/issues/issues/1452

2022-08-07 16:16 UTC, tituspijean commented
Nice!

One remark, Friendica is listed as a potential alternative to Diaspora, but not the other way around. Is that OK?

2022-08-07 16:55 UTC, ericgaspar requested changes
Add some caps

2022-08-07 16:55 UTC, ericgaspar commented on apps.json
> +            "Github"
```suggestion
            "GitHub"
```

2022-08-07 16:55 UTC, ericgaspar commented on apps.json
> +            "Github"
```suggestion
            "GitHub"
```

2022-08-07 16:55 UTC, ericgaspar commented on apps.json
> +            "Youtube"
```suggestion
            "YouTube"
```

2022-08-07 16:55 UTC, ericgaspar commented on apps.json
> +            "lastpass"
```suggestion
            "1Password",
            "Dashlane",
            "Enpass",
            "LastPass"
```

2022-08-07 16:55 UTC, ericgaspar commented on apps.json
> +            "trello"
```suggestion
            "Trello"
```

2022-08-07 16:55 UTC, ericgaspar commented on apps.json
> +            "Quicktime",
```suggestion
            "QuickTime",
```

2022-08-07 16:55 UTC, ericgaspar commented on apps.json
> +            "budgea",
```suggestion
            "Budgea",
```

2022-08-07 16:55 UTC, ericgaspar commented on apps.json
> +            "mint"
```suggestion
            "Mint"
```

2022-08-07 16:55 UTC, ericgaspar commented on apps.json
> +            "reddit"
```suggestion
            "Reddit"
```

2022-08-07 16:55 UTC, ericgaspar commented on apps.json
> +            "dokeos"
```suggestion
            "Dokeos"
```

2022-08-07 16:55 UTC, ericgaspar commented on apps.json
> +            "msn"
```suggestion
            "MSN"
```

2022-08-07 16:55 UTC, ericgaspar commented on apps.json
> +            "yooz"
```suggestion
            "Exact Online",
            "WinBooks",
            "Yooz"
```

2022-08-07 16:55 UTC, ericgaspar commented on apps.json
> +            "Youtube"
```suggestion
            "YouTube"
```

2022-08-07 16:55 UTC, ericgaspar commented on apps.json
> +            "time machine"
```suggestion
            "Time Machine"
```

2022-08-07 16:55 UTC, ericgaspar commented on apps.json
> +            "delicious",
```suggestion
            "Delicious",
```

2022-08-07 16:55 UTC, ericgaspar commented on apps.json
> +            "wix"
```suggestion
            "Blogger",
            "Coldfusion",
            "Wix"
```

2022-08-07 16:55 UTC, ericgaspar commented on apps.json
> +            "Google groups"
```suggestion
            "Google Groups"
```

2022-08-07 16:55 UTC, ericgaspar commented on apps.json
> +            "trello"
```suggestion
            "Trello"
```

2022-08-07 16:55 UTC, ericgaspar commented on apps.json
> +            "locize",
```suggestion
            "Locize",
```

2022-08-07 16:55 UTC, ericgaspar commented on apps.json
> +            "trello"
```suggestion
            "Trello"
```

2022-08-07 16:55 UTC, ericgaspar commented on apps.json
> +            "wix"
```suggestion
            "Blogger",
            "Blogspot",
            "Wix"
```

2022-08-07 16:55 UTC, ericgaspar commented on apps.json
> +            "blogger",
```suggestion
            "Blogger",
```

2022-08-07 17:11 UTC, ketsapiwiq commented
> Nice!
> 
> One remark, Friendica is listed as a potential alternative to Diaspora, but not the other way around. Is that OK?

Didn't catch that one, I propose we remove this line, since the goal is not to show alternatives between open source projects but rather create one-way links from commercial/closed source software to open source software packaged into YunoHost.

2022-08-07 17:29 UTC, ericgaspar requested changes
I missed some caps...

2022-08-07 17:29 UTC, ericgaspar commented on apps.json
> +            "time machine"
```suggestion
            "Time Machine"
```

2022-08-07 17:29 UTC, ericgaspar commented on apps.json
> +            "Soundcloud",
```suggestion
            "SoundCloud",
```

2022-08-07 17:29 UTC, ericgaspar commented on apps.json
> +            "Filemaker",
```suggestion
            "FileMaker",
```

2022-08-07 17:29 UTC, ericgaspar commented on apps.json
> +            "doctolib"
```suggestion
            "Doctolib"
```

2022-08-07 17:29 UTC, ericgaspar commented on apps.json
> +            "tempomail",
```suggestion
            "spamGourmet",
            "Tempomail",
```

2022-08-07 17:29 UTC, ericgaspar commented on apps.json
> +            "Peregrine system (AssetCenter)",
```suggestion
            "Peregrine Systems (AssetCenter)",
```

2022-08-07 17:29 UTC, ericgaspar commented on apps.json
> +            "wix"
```suggestion
            "Wix"
```

2022-08-07 17:29 UTC, ericgaspar commented on apps.json
> +            "linxo",
```suggestion
            "Linxo",
```

2022-08-13 14:52 UTC, ericgaspar approved these changes

2022-08-15 09:43 UTC, tituspijean approved these changes

2022-08-15 09:49 UTC, merged