Update app's level
YunoHost/apps pull request #1584
Opened 2023-01-06 19:05 UTC by ericgaspar

2023-01-06 19:08 UTC, ericgaspar commented on apps.json
> -        "state": "notworking",
This was added on purpose. Proxytok is not working

2023-01-07 13:07 UTC, tituspijean reviewed
- [ ] Flarum should be level 8 (connection error in last test): https://ci-apps.yunohost.org/ci/job/11776

2023-01-07 13:13 UTC, tituspijean requested changes

2023-01-07 13:13 UTC, tituspijean commented on apps.json
> +        "level": 1,
```suggestion
        "level": 8,
```

as per https://ci-apps.yunohost.org/ci/job/12598

2023-01-07 17:15 UTC, tituspijean requested changes

2023-01-07 17:15 UTC, tituspijean commented on apps.json
> +        "state": "working",
```suggestion
        "category": "dev",
        "level": 6,
        "state": "working",
```

as per https://ci-apps.yunohost.org/ci/job/12594

2023-01-07 17:15 UTC, tituspijean commented on apps.json
> +        "level": 0,
```suggestion
        "level": 6,
```

as per https://ci-apps.yunohost.org/ci/job/12512
Upgrades tests will most likely fail, to be fixed in the repo.

2023-01-07 17:33 UTC, tituspijean approved these changes

2023-01-08 17:45 UTC, merged