Add iceshrimp to catalog
YunoHost/apps pull request #1927
Opened 2023-12-22 13:30 UTC by oufmilo

2023-12-22 15:02 UTC, ericgaspar requested changes

2023-12-22 15:02 UTC, ericgaspar commented on apps.toml
> +
is it working? 
```
if so state = "working"
else
state = "notworking"
```

2023-12-22 15:06 UTC, oufmilo commented
not working yet

Sent from [Proton Mail](https://proton.me/mail/home) for iOS

Le ven. 22 déc. 2023 à 16:02, eric_G ***@***.***(mailto:Le ven. 22 déc. 2023 à 16:02, eric_G <<a href=)> a écrit :

> @ericgaspar requested changes on this pull request.
>
> ---------------------------------------------------------------
>
> In [apps.toml](https://github.com/YunoHost/apps/pull/1927#discussion_r1435141821):
>
>> @@ -1527,6 +1527,11 @@ state = "working"
>  subtags = [ "programming" ]
>  url = "https://github.com/YunoHost-Apps/icecoder_ynh"
>
> +[iceshrimp]
> +category = "social_media"
> +potential_alternative_to = [ "X", "Threads", "Mastodon", "Pleroma", "Misskey", "Calckey" ]
> +url = "https://github.com/YunoHost-Apps/iceshrimp_ynh"
> +
>
> is it working?
>
> if so state = "working"
> else
> state = "notworking"
>
> —
> Reply to this email directly, [view it on GitHub](https://github.com/YunoHost/apps/pull/1927#pullrequestreview-1794606770), or [unsubscribe](https://github.com/notifications/unsubscribe-auth/AKUM565D7LJPZFJLCKRQRATYKWOINAVCNFSM6AAAAABA72YLHCVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTOOJUGYYDMNZXGA).
> You are receiving this because you authored the thread.Message ID: ***@***.***>

2023-12-22 15:52 UTC, oufmilo commented on apps.toml
> +
Not working for the moment

2023-12-23 14:25 UTC, ericgaspar approved these changes

2023-12-23 14:25 UTC, merged