Adding Hotglue app
YunoHost/apps pull request #2504
Opened 2024-08-06 15:19 UTC by k0a1a

Hi there, 

I packaged by own project to be installed on YunoHost.

Thank you!

2024-08-17 15:58 UTC, tituspijean commented
Welcome and thank you for the packaging!

Would you consider transferring the repository to the YunoHost-Apps organization if we invite you to it? It provides access to our CI servers to help your packaging and automagic update of the sources whenever the upstream app has a new release.

(it's totally fine refusing to do so too 😄)

2024-08-18 17:23 UTC, k0a1a commented
Hi,

thanks for accepting my contribution! YTes, I'd love to transfer the repo to YunoHost-Apps but it's seems I need to be added to the org first?

2024-08-21 22:38 UTC, OniriCorpe commented
invite sent ^w^

2024-08-24 16:44 UTC, ericgaspar requested changes

2024-08-24 16:44 UTC, ericgaspar commented on apps.toml
> +url = "https://github.com/k0a1a/hotglue_ynh"
```suggestion
url = "https://github.com/YunoHost-Apps/hotglue_ynh"
```

2024-08-24 16:44 UTC, ericgaspar approved these changes

2024-08-24 16:45 UTC, merged